# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IfJRpjP8M8JM-ObvROdCXW2PYk9Wrea
"""

import streamlit as st
import random

excuses = [
    "is logique… dans mon monde.",
    "J’ai une idée… risquée.",
    "Le mystère reste entier… comme moi.",
    "Je suis prêt… presque.",
    "J’ai une théorie du chaos… appliquée.",
    "Rien n’a de sens, donc relax.",
    "Je suis sérieux… parfois involontairement.",
    "J’ai une intuition… contradictoire.",
    "Le problème me suit, je le guide.",
    "Je suis clair… pour moi.",
    "J’ai une réponse… incorrecte.",
    "Le doute m’accompagne.",
    "Je suis en évolution… lente.",
    "J’ai une idée… dangereuse.",
    "Tout est flou, donc parfait."
]


memes = [
    "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",  # cerveau en feu
    "https://media.giphy.com/media/3o6Zt6ML6BklcajjsA/giphy.gif", # WTF
    "https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif",  # stupéfait
    "https://media.giphy.com/media/l41lFw057lAJQMwg0/giphy.gif", # ohlala
    "https://media.giphy.com/media/3oKIPwoeGErMmaI43C/giphy.gif", # LOL
    "https://media.giphy.com/media/xUPGcA7vT2sZl4eyko/giphy.gif", # mind blown
]

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Comic+Neue:wght@700&display=swap');
html, body, [class*="css"]  {
    font-family: 'Comic Neue', cursive;
}
.stApp {
    background: linear-gradient(135deg, #ff9a9e, #fad0c4);
    color: #333;
    min-height: 100vh;
    padding-top: 50px;
}
button[kind="primary"] {
    background-color: #4bc0ff !important;
    color: white !important;
    font-size: 20px;
    border-radius: 12px;
    padding: 10px 20px;
}
</style>
""", unsafe_allow_html=True)

# --- Titre ---
st.markdown("<h1 style='text-align: center; color: #ff4b5c;'>Choix du Jour, ta citation! 😂</h1>", unsafe_allow_html=True)

if st.button("🎲 Nouveau choix!"):
    quote = random.choice(excuses)
    meme = random.choice(memes)


    st.image(meme, width=300)

    st.markdown(
        f"""
        <div style="
            background: linear-gradient(135deg, #ffe29f, #ff9a9e);
            padding: 30px;
            border-radius: 20px;
            text-align: center;
            font-size: 28px;
            font-weight: bold;
            color: #333;
            box-shadow: 5px 5px 15px rgba(0,0,0,0.2);
        ">
            {quote}
        </div>
        """, unsafe_allow_html=True
    )